= Narayana OpenShift tools

This repository contains tools used for integration
of the Narayana transaction manager to OpenShift environment.

== Content

`txn-recovery-marker-jdbc-hibernate4`, `txn-recovery-marker-jdbc-hibernate5`, `txn-recovery-marker-jdbc-common`::
  Saving a simple marker, designed to determine a running transaction recovery pod, to database.
  We need a different versions for Hibernate 4 and Hibernate 5 as those versions are not well compatible.
  Hibernate is used as it abstracts us from different database vendors as saving the marker data
  has to be running on whatever database the JBoss EAP is ready to run with.

== How to release

Release is performed to JBoss Nexus and you need to have credentials for it.
The JBoss Nexus respository can be found at https://repository.jboss.org/nexus/.

Credentials for release needs to be setup in the `~/.m2/settings.xml`
where you link the repository id `jboss-releases-repository` with the username/password.

```xml
<server>
    <id>jboss-releases-repository</id>
    <username>[username]</username>
    <password>[password for jboss nexus connection]</password>
</server>
```

As the next step run the `mvn release` and proceed standard steps
(see details e.g. at http://maven.apache.org/maven-release/maven-release-plugin/usage.html)
while there is used nexus staging plugin for this purpose.

* `git checkout master`
* `git fetch upstream master`
* `git rebase upstream/master`
* `git push upstream master`
* `mvn javadoc:javadoc` - verification that there won't be any javadoc errors during `release:perform`
* `mvn release:clean`
* `mvn release:prepare`
* `mvn release:perform`

if you want to  just check if runs fine
`mvn release:prepare -DdryRun=true`

