= Hibernate 5 standalone application to save data to database

Command line application which saves simple data to database.
It uses Hibernate 5 API to define database schema and for persistng and querying records.

== How to run

The application is the command line tool - 
link:../txn-recovery-marker-jdbc-common#application-arguments-for-starting[check the command line arguments].

== Hibernate standalone app to save a simple marker data to the database table

Command line application which saves simple data to database.
It uses Hibernate API to generate database schema and for persistng and querying records.

== How to run

The application is expected to be started as modular application
under https://jboss-modules.github.io/jboss-modules/manual/#introduction[jboss modules].

=== JBoss modular system

See link:../txn-recovery-marker-jdbc-hibernate4#modular-system[]


== Running under JBoss EAP 7/WildFly module structure

First you will need the jdbc driver - see details at link:../txn-recovery-marker-jdbc-common#how-to-create-jdbc-module[]

As the second step you need to define this application to be a module. You have two options


=== Using `jboss-cli`

First option is using `jboss-cli` tool (either as `shell script` or `bat script`).

. start JBoss EAP 7/WildFly: `$JBOSS_HOME/bin/standalone.sh`
. start jboss-cli: `$JBOSS_HOME/bin/jboss-cli.sh -c`
. run command to add the application as module:

[source]
----
module add --name=io.narayana.openshift-recovery --resources=./txn-recovery-marker-jdbc-hibernate5/target/txn-recovery-marker-jdbc-hibernate5.jar:./txn-recovery-marker-jdbc-common/target/txn-recovery-marker-jdbc-common.jar --dependencies=javax.persistence.api,org.hibernate,org.postgresql,com.mysql,org.jboss.logging --main-class=io.narayana.openshift.txrecovery.Main
----

or with embedded server

[source]
----
$JBOSS_HOME/bin/jboss-cli.sh "embed-server --server-config=standalone.xml, module add --name=io.narayana.openshift-recovery --resources=./txn-recovery-marker-jdbc-hibernate5/target/txn-recovery-marker-jdbc-hibernate5.jar:./txn-recovery-marker-jdbc-common/target/txn-recovery-marker-jdbc-common.jar --dependencies=javax.persistence.api\,org.hibernate\,org.postgresql\,com.mysql\,org.jboss.logging --main-class=io.narayana.openshift.txrecovery.Main"
----

WARN: if you don't define both modules `org.postgresq` and `com.mysql` in prior to running the application,
then you consider define one of them as `optional="true"` (see https://jboss-modules.github.io/jboss-modules/manual/#manifest-dependencies)

=== Manual way to create jdbc driver module

. create directory `$JBOSS_HOME/modules/io/narayana/openshift-recovery/main/`
. copy the commons jar and hibernate 5 jar under the created directory (check naming in module.xml descriptor below)
. create file `module.xml` under the created directory. The content of the file will be

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.1" name="io.narayana.openshift-recovery">
    <main-class name="io.narayana.openshift.txrecovery.Main"/>
    <resources>
        <resource-root path="txn-recovery-marker-jdbc-common.jar"/>
        <resource-root path="txn-recovery-marker-jdbc-hibernate5.jar"/>
    </resources>
    <dependencies>
        <module name="javax.persistence.api"/>
        <module name="org.hibernate"/>
        <module name="org.jboss.logging"/>
        <module name="org.postgresql" optional="true"/>
        <module name="com.mysql" optional="true"/>
    </dependencies>
</module>
----

== Go and run

There are several required properties for the program may run.
First you need to define the connection. The required parameters are

* user (`-u`) and password (`-s`)
* url (`-l`) or all parameters of hostname (`-o`), port (`-p`), database (`-d`)
* database type (`-y`) or all parameters of hibernate dialect (`-i`), JDBC driver class name (`-j`)

As example let's run against a PostgreSQL database

[source,bash]
----
export JBOSS_HOME=<path/to/jboss-eap-7/app/server>
# java -jar $JBOSS_HOME/jboss-modules.jar -mp $JBOSS_HOME/modules/ io.narayana.openshift-recovery -y <db_type> -o <db_host> -p <db_port> -d <db_name> -u <db_user> -s <db_password> -t <table_name_for_storing> -c <command> -a <app_pod_name> -r <recovery_pod_name>
java -jar $JBOSS_HOME/jboss-modules.jar -mp $JBOSS_HOME/modules/ io.narayana.openshift-recovery -y postgresql -o localhost -p 5432 -d test -u test -s test -t txndata -c insert -a appname -r recname
----

NOTE: for debugging enhance `java` command with `-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=y`

